name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm ci
        working-directory: turtle-portfolio

      - name: Run Tests
        run: npm test
        working-directory: turtle-portfolio

      - name: Build
        run: npm run build
        working-directory: turtle-portfolio
